### ISSUE TITLE
can't launch gulp

### ISSUE THREAD

**Issue by bpongy** [PrestaShop/community-theme-16#247]
There's a lot of errors in gulp file when trying to launch with gulp 4.

`
% gulp compile-css
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Task function must be specified
`

syntax & ideas here: https://gist.github.com/demisx/beef93591edc1521330a

**Comment by bpongy** [comment]
I can launch the sass watcher, but I have to remove tasks "default" and "build" to avoid fatal error.
Then:

```
gulp.task('axome-watch', function () {
    gulp.watch('./themes/' + options.themeName + '/sass/**/*.scss');
});

gulp.task('axome', gulp.parallel('axome-watch'));
```

...and launch with `gulp axome`

syntax is not the same with gulp 4 :/

**Comment by gskema** [comment]
Hello,
- How did you get gulp 4? Is it out yet?
- Which version of the theme do you use?

The old script uses global installation of gulp, so if you upgrade your global installation of gulp to `v4`, the the script won't work. That's why we introduced local gulp to avoid such problems: https://github.com/PrestaShop/community-theme-16/pull/246

As far as I know `"gulp": "^3.9.0"` in `package.json` will only produce versions `3.x.x`
