### ISSUE TITLE
Problems in file product.tpl

### ISSUE THREAD

**Issue by eriknuds** [PrestaShop/community-theme-16#259]
* In file product.tpl, id="availability_statut" should probably be changed to id="availability_status". Notice the t vs s on the end.

* In file product.tpl, in paragraph `<p id="product-availability">`, the line with `$product->quantity == 1` prints the `id="quantityAvailableTxtMultiple">{l s='Items'}` and the line with `$product->quantity > 1` prints the `id="quantityAvailableTxt">{l s='Item'}` - I guess this should be the other way around.

* The current release is getting old. Lots of new submits...

**Comment by gskema** [comment]
@eriknuds

https://github.com/PrestaShop/PrestaShop/blob/1.6.1.x/themes/default-bootstrap/product.tpl#L214
It's `availability_statut` in default theme, meaning other 3rd party modules may be dependent on this ID.

https://github.com/PrestaShop/community-theme-16/blob/dev/themes/community-theme-16/product.tpl#L146

Is correct as well, because the `{if ...}` statement **hides** the labels. E.g. If `qty > 1` then `'Item'` label is hidden
