### ISSUE TITLE
Remove "display all pictures toggle"

### ISSUE THREAD

**Issue by gskema** [PrestaShop/community-theme-16#62]
In the product page

**Comment by kpodemski** [comment]
Why?

**Comment by gskema** [comment]
If we make a slider for thumbnails, why should there even be such a button? Its useless imo.

**Comment by kpodemski** [comment]
No because changing for example color can change also related photos, let's assume that we have:
1 base photo, for eg cover
2 black version photos
2 white version photos

someone clicks "Black" color attribute, script filter these photos and display only 2 black version photos, what with situation where someone wants to see cover one more time? I had a few better examples but I'm sure you get a point :)

**Comment by gskema** [comment]
I've never encoutered that the script leaves only the black photos if black color is selected.

**Comment by kpodemski** [comment]
Really? :D You can assign selected photos to selected attributes, this is used most of the time to assign for eg. color attribute to specific photos :)

See this little example:
http://preview.prestahome.com/tf/vitalia/vegetables/9-pepper.html#

**Comment by schibu83** [comment]
:+1: @kpodemski This function is very usefull and should NOT be removed

**Comment by gskema** [comment]
#162
